### ISSUE TITLE
Is there a list of SSG or flat file CMSes too?

### ISSUE THREAD

**Issue by Socialinsect** [bevry/staticsitegenerators-website#26]
There is [Grav](https://github.com/getgrav/grav) in the list and it is not static site generator, is it?

**Comment by balupton** [comment]
See https://github.com/bevry/staticsitegenerators-list for criteria.

I don't know other listings like what you are after. We plan on upgrading our listing to make the different types more acessible: https://github.com/bevry/staticsitegenerators-list/issues/220

**Comment by Socialinsect** [comment]
Thanks for the quick answer. Separating will save time for a lot of people comparing and looking for a static site generator.

**Comment by balupton** [comment]
This is accomplishable by people filling in the `is` field on the entries in the listing https://github.com/bevry/staticsitegenerators-list
