### ISSUE TITLE
Please update more often

### ISSUE THREAD

**Issue by jhabdas** [bevry/staticsitegenerators-website#27]
I popped this into Wikipedia. It would be nice if it could be set on a cron job to regenerate at least once a week.

https://en.wikipedia.org/wiki/Static_web_page - The Wiki linking
https://gitea.io/ - This might help
https://habd.as/zero-to-http-2-aws-hugo/#comment-3150340376 - Idea to set-up a task runner using Serverless for the cron job

**Comment by balupton** [comment]
It already has continuous integration and deployment, so not sure what more you want, as every commit is deployed within minutes if tests pass.

**Comment by balupton** [comment]
I should note that any passing commit on the listing repo will trigger the CI ans CD for this repo too

**Comment by jhabdas** [comment]
Your welcome.
